# Generated by Django 4.1.7 on 2024-01-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testing',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='testing',
            name='imagePath',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='testing',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
