# Generated by Django 4.1.7 on 2024-01-15 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=50)),
                ('exercise_image', models.ImageField(blank=True, null=True, upload_to='exercise_images')),
            ],
        ),
        migrations.CreateModel(
            name='Testing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('imagePath', models.ImageField(blank=True, null=True, upload_to='testing_images')),
                ('description', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingWithExercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_1_set', to='Website_training_objects.exercise')),
                ('exercise_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_2_set', to='Website_training_objects.exercise')),
                ('exercise_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_3_set', to='Website_training_objects.exercise')),
                ('exercise_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_4_set', to='Website_training_objects.exercise')),
                ('exercise_5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_5_set', to='Website_training_objects.exercise')),
                ('exercise_6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_6_set', to='Website_training_objects.exercise')),
                ('exercise_7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_7_set', to='Website_training_objects.exercise')),
                ('exercise_8', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_8_set', to='Website_training_objects.exercise')),
                ('exercise_9', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_9_set', to='Website_training_objects.exercise')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website_training_objects.training')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('training_with_exercises', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website_training_objects.trainingwithexercises')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveSmallIntegerField()),
                ('reps', models.PositiveSmallIntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website_training_objects.exercise')),
                ('training_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website_training_objects.traininghistory')),
            ],
        ),
        migrations.AddField(
            model_name='training',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website_training_objects.userprofile'),
        ),
    ]
